/**
 * DATA PARA PROVÕES COMPLETOS (ESTILO ENEM OFICIAL)
 * Provão #1 expandido para 45 questões + Redação
 */

const PROVOES = [
  {
    id: 101, num: "01", title: "Provão Geral ENEM #1", mat: "provao", matLabel: "Provão Geral", time: "4h 30min", qs: 45, status: "new",
    essayPrompt: "Os desafios da educação inclusiva e o papel das tecnologias assistivas no Brasil.",
    questoes: [
      /* LINGUAGENS (1-12) */
      { id: "p1q1", n: 1, enunciado: "No poema 'O Bicho', Manuel Bandeira descreve uma cena de miséria extrema. A intenção do autor é:", alternativas: ["A) Romantizar a pobreza urbana", "B) Criticar a desumanização causada pela fome", "C) Exaltar a resiliência do povo", "D) Analisar a fauna das cidades", "E) Propor uma reforma estética"], gabarito: "B", explicacao: "O autor usa o bicho como metáfora para o homem degradado pela miséria." },
      { id: "p1q2", n: 2, enunciado: "A função da linguagem em que o emissor foca na própria mensagem, explorando recursos sonoros e rítmicos, é a:", alternativas: ["A) Referencial", "B) Apelativa", "C) Poética", "D) Fática", "E) Metalinguística"], gabarito: "C", explicacao: "A função poética foca na estética e construção da mensagem." },
      { id: "p1q3", n: 1, enunciado: "A variação linguística que ocorre devido à região geográfica do falante é chamada de:", alternativas: ["A) Diastrática", "B) Diatópica", "C) Diafásica", "D) Diacrônica", "E) Gíria técnica"], gabarito: "B", explicacao: "Diatópica refere-se ao lugar (topos)." },
      { id: "p1q4", n: 3, enunciado: "Nas artes plásticas, o Cubismo caracteriza-se pela:", alternativas: ["A) Utilização de cores pastéis", "B) Geometrização das formas e simultaneidade de perspectivas", "C) Representação fiel da natureza", "D) Ausência total de formas", "E) Valorização do claro-escuro"], gabarito: "B", explicacao: "Picasso e Braque fragmentavam a realidade em planos geométricos." },
      { id: "p1q5", n: 2, enunciado: "O gênero textual marcado pela opinião do veículo de comunicação, geralmente sem assinatura de autor individual, é o:", alternativas: ["A) Crônica", "B) Editorial", "C) Reportagem", "D) Notícia", "E) Carta do leitor"], gabarito: "B", explicacao: "Editoriais expressam a posição oficial do jornal/revista." },
      { id: "p1q6", n: 1, enunciado: "O uso de 'vossa mercê' até chegar a 'você' exemplifica uma variação:", alternativas: ["A) Social", "B) Regional", "C) Histórica", "D) Estilística", "E) Formal"], gabarito: "C", explicacao: "Variação diacrônica ocorre através do tempo." },
      { id: "p1q7", n: 2, enunciado: "A intertextualidade ocorre quando:", alternativas: ["A) Um texto ignora outros textos", "B) Um texto dialoga ou faz referência a outro texto", "C) O texto é exclusivamente visual", "D) O autor esquece o tema central", "E) Não há pontuação no texto"], gabarito: "B", explicacao: "É o diálogo entre obras." },
      { id: "p1q8", n: 1, enunciado: "O Naturalismo na literatura brasileira tem como principal obra:", alternativas: ["A) O Cortiço", "B) Iracema", "C) Dom Casmurro", "D) Memórias Póstumas", "E) O Guarani"], gabarito: "A", explicacao: "Aluísio Azevedo retrata o coletivo e o determinismo biológico." },
      { id: "p1q9", n: 3, enunciado: "A coesão textual é garantida principalmente pelo uso correto de:", alternativas: ["A) Adjetivos", "B) Conectivos (conjunções e pronomes)", "C) Pontos de exclamação", "D) Verbos no passado", "E) Figuras de linguagem"], gabarito: "B", explicacao: "Conectivos ligam as partes do texto logicamente." },
      { id: "p1q10", n: 2, enunciado: "O Simbolismo valoriza:", alternativas: ["A) A razão e a ciência", "B) O subjetivismo e o misticismo", "C) A descrição objetiva da realidade", "D) O cotidiano burguês", "E) A política partidária"], gabarito: "B", explicacao: "Foco no inconsciente, sonhos e sugestão." },
      { id: "p1q11", n: 1, enunciado: "Em 'Quem tem boca vai a Roma', a figura de linguagem presente é:", alternativas: ["A) Metáfora", "B) Metonímia", "C) Hipérbole", "D) Eufemismo", "E) Antítese"], gabarito: "B", explicacao: "Substituição de 'quem fala' por 'quem tem boca' (parte pelo todo)." },
      { id: "p1q12", n: 2, enunciado: "O Modernismo de 1922 buscava:", alternativas: ["A) Copiar os modelos europeus", "B) Uma identidade nacional brasileira e a liberdade formal", "C) Voltar ao estilo clássico", "D) Manter a rima obrigatória", "E) Proibir o uso de gírias"], gabarito: "B", explicacao: "Ruptura com o passado acadêmico." },

      /* CIÊNCIAS HUMANAS (13-24) */
      { id: "p1q13", n: 1, enunciado: "A democracia ateniense na Grécia Antiga era:", alternativas: ["A) Universal e inclusiva", "B) Direta, mas restrita a cidadãos (homens, livres e adultos)", "C) Representativa como a atual", "D) Uma monarquia absolutista", "E) Exclusiva para estrangeiros"], gabarito: "B", explicacao: "Mulheres, escravos e estrangeiros não participavam." },
      { id: "p1q14", n: 2, enunciado: "O Feudalismo foi o sistema econômico predominante na:", alternativas: ["A) Idade Antiga", "B) Idade Média", "C) Idade Moderna", "D) Idade Contemporânea", "E) Pré-história"], gabarito: "B", explicacao: "Marcado pela ruralização e relação entre suseranos e vassalos." },
      { id: "p1q15", n: 3, enunciado: "A Expansão Marítima Portuguesa teve como objetivo inicial:", alternativas: ["A) Descobrir o ouro nas Américas", "B) Encontrar uma nova rota para as Índias (especiarias)", "C) Fugir da Peste Negra", "D) Conquistar a Antártica", "E) Aliar-se aos mouros"], gabarito: "B", explicacao: "Busca pelo comércio direto de especiarias no Oriente." },
      { id: "p1q16", n: 1, enunciado: "O Ciclo do Ouro no Brasil (Séc XVIII) causou:", alternativas: ["A) O esvaziamento das cidades mineiras", "B) O deslocamento do eixo econômico para o Sudeste", "C) A independência imediata do Brasil", "D) O fim do tráfico negreiro", "E) A aliança com os holandeses"], gabarito: "B", explicacao: "O Rio de Janeiro tornou-se a capital em 1763 por causa do ouro." },
      { id: "p1q17", n: 2, enunciado: "A Revolução Francesa (1789) teve como lema:", alternativas: ["A) Ordem e Progresso", "B) Liberdade, Igualdade e Fraternidade", "C) Deus, Pátria e Família", "D) Paz, Pão e Terra", "E) Trabalho e Liberdade"], gabarito: "B", explicacao: "Liberté, Égalité, Fraternité." },
      { id: "p1q18", n: 3, enunciado: "A globalização intensificou a desigualdade social no mundo porque:", alternativas: ["A) Todos os países ficaram ricos igualmente", "B) Concentrou capital em empresas transnacionais e países desenvolvidos", "C) Acabou com a tecnologia", "D) Proibiu a migração de pessoas", "E) Eliminou as fronteiras físicas"], gabarito: "B", explicacao: "Aumentou a abismo entre o Norte e o Sul global." },
      { id: "p1q19", n: 1, enunciado: "O que caracteriza a hidrografia brasileira?", alternativas: ["A) Rios curtos e congelados", "B) Rios extensos, perenes e regime pluvial", "C) Ausência de rios de planalto", "D) Predomínio de lagos salgados", "E) Poucos rios navegáveis"], gabarito: "B", explicacao: "O Brasil é rico em águas doces superficiais dependentes de chuvas." },
      { id: "p1q20", n: 2, enunciado: "A Revolução Industrial consolidou o sistema:", alternativas: ["A) Feudal", "B) Socialista", "C) Capitalista", "D) Mercantilista", "E) Comunista"], gabarito: "C", explicacao: "Propriedade privada, lucro e trabalho assalariado." },
      { id: "p1q21", n: 1, enunciado: "A 'Era Vargas' (1930-1945) foi importante para:", alternativas: ["A) A volta da Monarquia", "B) A industrialização nacional e leis trabalhistas", "C) O fim da exportação de café", "D) A venda da Petrobras", "E) O isolamento diplomático do Brasil"], gabarito: "B", explicacao: "Vargas criou a CLT e impulsionou a indústria de base." },
      { id: "p1q22", n: 2, enunciado: "O Iluminismo defendia:", alternativas: ["A) O poder divino dos Reis", "B) O uso da razão e a ciência sobre a fé", "C) A volta ao sistema de tribos", "D) A escravidão africana", "E) O misticismo religioso"], gabarito: "B", explicacao: "Século das Luzes focado na racionalidade humano." },
      { id: "p1q23", n: 3, enunciado: "A urbanização brasileira acelerou após:", alternativas: ["A) 1500", "B) 1950", "C) 1822", "D) 1888", "E) 1914"], gabarito: "B", explicacao: "Industrialização atraiu pessoas do campo para as cidades." },
      { id: "p1q24", n: 1, enunciado: "O conceito de 'Mais-Valia' de Karl Marx refere-se à:", alternativas: ["A) Diferença entre o valor produzido pelo operário e o salário pago", "B) Aumento do preço dos produtos por impostos", "C) Valorização das ações na bolsa", "D) Ajuda humanitária internacional", "E) Redução da carga horária"], gabarito: "A", explicacao: "É a base da exploração capitalista segundo Marx." },

      /* CIÊNCIAS DA NATUREZA (25-36) */
      { id: "p1q25", n: 1, enunciado: "A principal organela responsável pela respiração celular é:", alternativas: ["A) Cloroplasto", "B) Mitocôndria", "C) Ribossomo", "D) Lisossomo", "E) Vacúolo"], gabarito: "B", explicacao: "A mitocôndria gera ATP através da respiração." },
      { id: "p1q26", n: 1, enunciado: "Qual o pH de uma solução considerada neutra?", alternativas: ["A) 0", "B) 7", "C) 14", "D) 5", "E) 10"], gabarito: "B", explicacao: "pH 7 é o ponto neutro (ex: água pura)." },
      { id: "p1q27", n: 2, enunciado: "A Primeira Lei de Newton afirma que:", alternativas: ["A) F = m . a", "B) Toda ação gera uma reação", "C) Um corpo em repouso tende a permanecer em repouso (Inércia)", "D) A gravidade é constante", "E) O tempo é relativo"], gabarito: "C", explicacao: "Inércia é a resistência à mudança de estado de repouso ou movimento." },
      { id: "p1q28", n: 3, enunciado: "O processo de divisão celular que produz gametas é a:", alternativas: ["A) Mitose", "B) Meiose", "C) Fissão binária", "D) Osmose", "E) Tradução"], gabarito: "B", explicacao: "Meiose reduz o número de cromossomos pela metade." },
      { id: "p1q29", n: 2, enunciado: "As propriedades coligativas dependem do:", alternativas: ["A) Tipo de soluto", "B) Número de partículas do soluto", "C) Cor da solução", "D) Recipiente utilizado", "E) Volume da água"], gabarito: "B", explicacao: "Dependem apenas da quantidade de partículas." },
      { id: "p1q30", n: 1, enunciado: "O aquecimento global é agravado pela queima de:", alternativas: ["A) Energia solar", "B) Combustíveis fósseis (petróleo, carvão)", "C) Água", "D) Vento", "E) Hidrogênio verde"], gabarito: "B", explicacao: "Liberação massiva de CO2 na atmosfera." },
      { id: "p1q31", n: 2, enunciado: "As ondas sonoras são classificadas como:", alternativas: ["A) Eletromagnéticas", "B) Mecânicas", "C) Transversais", "D) Radiativas", "E) Estáticas"], gabarito: "B", explicacao: "Som necessita de um meio material para se propagar." },
      { id: "p1q32", n: 1, enunciado: "Os estômatos nas plantas servem para:", alternativas: ["A) Absorver água do solo", "B) Trocas gasosas e transpiração", "C) Proteção contra insetos", "D) Produzir sementes", "E) Armazenar amido"], gabarito: "B", explicacao: "Localizados nas folhas para respiração e transpiração." },
      { id: "p1q33", n: 3, enunciado: "A radioatividade é a emissão de energia de um:", alternativas: ["A) Átomo estável", "B) Núcleo instável", "C) Elétron livre", "D) Próton isolado", "E) Neutrino"], gabarito: "B", explicacao: "Emissão de partículas/radiação para buscar estabilidade." },
      { id: "p1q34", n: 2, enunciado: "A tabela periódica é organizada por:", alternativas: ["A) Nome das letras", "B) Ordem alfabética", "C) Número atômico (Z)", "D) Cor dos elementos", "E) Tamanho do átomo"], gabarito: "C", explicacao: "Organização sequencial por número de prótons." },
      { id: "p1q35", n: 1, enunciado: "O daltonismo é uma condição ligada ao cromossomo:", alternativas: ["A) Y", "B) X", "C) 21", "D) Mitocondrial", "E) Autossômico"], gabarito: "B", explicacao: "Herança genética recessiva ligada ao sexo." },
      { id: "p1q36", n: 2, enunciado: "A unidade de medida da Força é o:", alternativas: ["A) Joule", "B) Watt", "C) Newton", "D) Ampere", "E) Volt"], gabarito: "C", explicacao: "Em homenagem a Isaac Newton (N)." },

      /* MATEMÁTICA (37-45) */
      { id: "p1q37", n: 1, enunciado: "Se uma mercadoria de R$ 200,00 sobe 10%, o novo preço é:", alternativas: ["A) R$ 210,00", "B) R$ 220,00", "C) R$ 202,00", "D) R$ 240,00", "E) R$ 250,00"], gabarito: "B", explicacao: "10% de 200 é 20. 200+20 = 220." },
      { id: "p1q38", n: 2, enunciado: "A área de um círculo é calculada por:", alternativas: ["A) 2 . pi . r", "B) pi . r²", "C) base . altura", "D) pi . r³", "E) L²"], gabarito: "B", explicacao: "Pi vezes o raio ao quadrado." },
      { id: "p1q39", n: 3, enunciado: "A probabilidade de sair Cara em uma moeda é:", alternativas: ["A) 1/3", "B) 1/2", "C) 1/4", "D) 1/1", "E) 0"], gabarito: "B", explicacao: "Um resultado favorável em dois possíveis (50%)." },
      { id: "p1q40", n: 1, enunciado: "Se um triângulo tem base 10 e altura 5, sua área é:", alternativas: ["A) 50", "B) 25", "C) 100", "D) 15", "E) 5"], gabarito: "B", explicacao: "(Base x Altura) / 2 = (10x5)/2 = 25." },
      { id: "p1q41", n: 2, enunciado: "O Teorema de Pitágoras é aplicado em triângulos:", alternativas: ["A) Isósceles", "B) Equiláteros", "C) Retângulos", "D) Escalenos", "E) Acutângulos"], gabarito: "C", explicacao: "Triângulos que possuem um ângulo de 90°." },
      { id: "p1q42", n: 3, enunciado: "Logaritmo de 100 na base 10 é:", alternativas: ["A) 1", "B) 2", "C) 10", "D) 100", "E) 0"], gabarito: "B", explicacao: "10 elevado ao quadrado é 100." },
      { id: "p1q43", n: 1, enunciado: "Uma escala de 1:100 significa que 1cm no mapa vale:", alternativas: ["A) 1 metro", "B) 100 metros", "C) 10 quilômetros", "D) 1 milímetro", "E) 10 metros"], gabarito: "A", explicacao: "100cm = 1 metro." },
      { id: "p1q44", n: 2, enunciado: "O MMC de 4 e 6 é:", alternativas: ["A) 2", "B) 12", "C) 24", "D) 10", "E) 8"], gabarito: "B", explicacao: "O menor múltiplo comum é 12." },
      { id: "p1q45", n: 3, enunciado: "A média aritmética de 5, 10 e 15 é:", alternativas: ["A) 5", "B) 10", "C) 15", "D) 30", "E) 12"], gabarito: "B", explicacao: "(5+10+15)/3 = 30/3 = 10." }
    ]
  }
];

if (typeof SIMULADOS !== 'undefined') {
  SIMULADOS.push(...PROVOES);
}
